# Copiar este archivo a application-dev.properties y poner valores reales.

PORT=4000
DATABASE_URL=poner la verdadera
DB_USERNAME=root
DB_PASSWORD=root

# Generar con: openssl rand hex 32
JWT_SECRET=un valor aleatorio
JWT_EXPIRATION_MS=86400000

CORS_ORIGINS=http://localhost:5173
