# Copiar este archivo a application-dev.properties y poner tus valores
# reales de MySQL local. application-dev.properties NUNCA se sube al repo.

PORT=8080
DATABASE_URL=jdbc:mysql://localhost:3306/alertasegura
DB_USERNAME=root
DB_PASSWORD=clave_personal_local

# Generar con: openssl rand -hex 32
JWT_SECRET=generar_codigo
#generar uno con: openssl rand -hex 32
JWT_EXPIRATION=86400000